language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build
deploy:
  provider: gae
  skip_cleanup: true
  keyfile: service-account.json
  project: catch-of-the-day-platform
  default: true
  on:
    all_branches: true
before_install:
- openssl aes-256-cbc -K $encrypted_82bc60b1bcae_key -iv $encrypted_82bc60b1bcae_iv
  -in service-account.json.enc -out service-account.json -d
